export const booksMockData = [
    {
      id: 1,
      Title: "The Great Gatsby",
      Language: "English",
      TotalCopies: 100,
      AvailableCopies: 75,
      Rating: 4.5,
      Reviews: 120,
      BookFormat: "Hardcover",
      ShelfLocation: "A1",
      Condition: "Good",
      BookImage: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/5315e910834791.560ebecae31ff.jpg",
      AuthorId: 1,
      GenreId: 1,
      LibraryId: 1,
      PublisherId: 1,
    },
    {
      id: 2,
      Title: "To Kill a Mockingbird",
      Language: "English",
      TotalCopies: 90,
      AvailableCopies: 60,
      Rating: 4.8,
      Reviews: 150,
      BookFormat: "Paperback",
      ShelfLocation: "B2",
      Condition: "Excellent",
      BookImage: "https://cdn2.penguin.com.au/covers/original/9781784752637.jpg",
      AuthorId: 2,
      GenreId: 2,
      LibraryId: 2,
      PublisherId: 2,
    },
    {
      id: 3,
        Title: "Harry Potter and the Sorcerer's Stone",
        Language: "English",
        TotalCopies: 120,
        AvailableCopies: 80,
        Rating: 4.7,
        Reviews: 180,
        BookFormat: "Hardcover",
        ShelfLocation: "C3",
        Condition: "Excellent",
        BookImage: "https://img.moviesrankings.com/t/p/w1280/fbxQ44VRdM2PVzHSNajUseUteem.jpg",
        AuthorId: 3,
        GenreId: 3,
        LibraryId: 1,
        PublisherId: 3,
      },
      {
      id: 4,
        Title: "The Hobbit",
        Language: "English",
        TotalCopies: 80,
        AvailableCopies: 50,
        Rating: 4.6,
        Reviews: 150,
        BookFormat: "Paperback",
        ShelfLocation: "D1",
        Condition: "Good",
        BookImage: "http://1.bp.blogspot.com/-tz40y0OlrCc/VGfG-NmL_AI/AAAAAAAAAJg/JVArqytkaOE/s1600/81Dd%2BimpKAL.jpg",
        AuthorId: 4,
        GenreId: 4,
        LibraryId: 2,
        PublisherId: 4,
      },
      {
      id: 5,
        Title: "The Catcher in the Rye",
        Language: "English",
        TotalCopies: 95,
        AvailableCopies: 65,
        Rating: 4.3,
        Reviews: 130,
        BookFormat: "Paperback",
        ShelfLocation: "A2",
        Condition: "Fair",
        BookImage: "https://tse2.mm.bing.net/th?id=OIP.EhOg_5HJS4hDMONihBcEoQHaMP&pid=Api&P=0&h=220",
        AuthorId: 5,
        GenreId: 5,
        LibraryId: 3,
        PublisherId: 5,
      },
      {
      id: 6,
        Title: "Pride and Prejudice",
        Language: "English",
        TotalCopies: 110,
        AvailableCopies: 75,
        Rating: 4.9,
        Reviews: 200,
        BookFormat: "Hardcover",
        ShelfLocation: "B3",
        Condition: "Excellent",
        BookImage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471134746/pride-and-prejudice-9781471134746_hr.jpg",
        AuthorId: 1,
        GenreId: 1,
        LibraryId: 1,
        PublisherId: 3,
      },
      {
      id: 7,
        Title: "One Hundred Years of Solitude",
        Language: "Spanish",
        TotalCopies: 85,
        AvailableCopies: 55,
        Rating: 4.8,
        Reviews: 190,
        BookFormat: "Paperback",
        ShelfLocation: "C1",
        Condition: "Excellent",
        BookImage: "http://1.bp.blogspot.com/-hM-iSBej13E/T9GuLsnNjRI/AAAAAAAADHw/zb_HPkmqkzA/s1600/onehundredyearsofsolitude.jpg",
        AuthorId: 2,
        GenreId: 2,
        LibraryId: 2,
        PublisherId: 4,
      },
      {
      id: 8,
        Title: "The Lord of the Rings",
        Language: "English",
        TotalCopies: 100,
        AvailableCopies: 70,
        Rating: 4.8,
        Reviews: 220,
        BookFormat: "Hardcover",
        ShelfLocation: "D2",
        Condition: "Excellent",
        BookImage: "https://i.thenile.io/r1000/9780618645619.jpg?r=5eb588fe0f142",
        AuthorId: 3,
        GenreId: 3,
        LibraryId: 3,
        PublisherId: 5,
      },
      {
      id: 9,
        Title: "Crime and Punishment",
        Language: "Russian",
        TotalCopies: 75,
        AvailableCopies: 45,
        Rating: 4.2,
        Reviews: 110,
        BookFormat: "Paperback",
        ShelfLocation: "A3",
        Condition: "Fair",
        BookImage: "https://imgv2-1-f.scribdassets.com/img/word_document/342870203/original/0f5318de2d/1571483150?v=1",
        AuthorId: 4,
        GenreId: 4,
        LibraryId: 1,
        PublisherId: 3,
      },
      {
      id: 10,
        Title: "The Great Expectations",
        Language: "English",
        TotalCopies: 95,
        AvailableCopies: 60,
        Rating: 4.6,
        Reviews: 160,
        BookFormat: "Hardcover",
        ShelfLocation: "B1",
        Condition: "Good",
        BookImage: "https://imgv2-1-f.scribdassets.com/img/word_document/251891517/original/41c439d8f6/1626299276?v=1",
        AuthorId: 5,
        GenreId: 5,
        LibraryId: 2,
        PublisherId: 4,
      },
  ];
  
